### ISSUE TITLE
Docker build broken

### ISSUE THREAD

**Issue by scjody** [plotly/falcon-sql-client#291]
The Docker build for this repo has been broken since https://github.com/plotly/falcon-sql-client/pull/277 was merged last Friday.

You can see Docker build status here: https://quay.io/repository/plotly/falcon-sql-client?tab=builds (a build is triggered on each push), or run `docker build .` in the top directory of the project regularly. If this is too much to deal with, I suggest integrating something like https://github.com/remind101/quayd to add status checks (like with other CI tools), or you could switch the Docker build to be done on CircleCI's infrastructure (as part of the normal CI run) rather than Quay.

Anyway, this needs to be fixed or else On-Prem 2.3.0 won't include any changes made after https://github.com/plotly/falcon-sql-client/commit/69905b7afa0c9923423db6c45bacad501040a9a9 (the last commit that built successfully).

@n-riesco @tarzzz @chriddyp FYI

**Comment by n-riesco** [comment]
@scjody Fixed in https://github.com/plotly/falcon-sql-client/pull/292

BTW, although I can open https://quay.io/repository/plotly/falcon-sql-client?tab=builds , I'm denied access when I click on a particular build.

I see difficulties with the integration of `docker build` into our PR builds using either of the options suggested, `quayd` or `CircleCI`:
- running `docker build` on `CircleCI` would likely more than double the build times (even if we manage to cache all the `docker pull`s)
- `quayd` sounds doable but I'm not sure it's worth it, because if I understood correctly, we'd have to maintain a server to run `quayd`

I like the idea of having a `release` and a `freeze` branch. If we do that, we could have a checklist of things to do before merging `freeze` into `release`. In that checklist we could have that the condition that the `quay` build succeeds in `freeze`. From the maintainer's point of view, this option would minimise the time we spent on ensuring `Dockerfile` works on prem.

**Comment by scjody** [comment]
(I am dealing with the Quay access issue by private message on Slack.)

@n-riesco Thanks for fixing this!

Re: `docker build` on CircleCI, you can do this in parallel with the rest of the tests. Take a look at what we're doing for in https://github.com/plotly/image-exporter .

It does look like `quayd` requires a server, but those are pretty cheap these days. We have quite a few things deployed on Heroku as well as Google Cloud Platform and if you want to experiment with either of those we can give you access.

I'll explain the branching more in https://github.com/plotly/streambed/issues/10382 to keep the discussion in one place.
