### ISSUE TITLE
Resize handle on the editor form

### ISSUE THREAD

**Issue by titanomachy** [plotly/falcon-sql-client#311]
The only option right now is to hide or show the editor form. I would prefer a resize handle on the form, so that I can enter queries while viewing the graphs. 

There is an issue in the Code Mirror repository about a missing resize handle: https://github.com/codemirror/CodeMirror/issues/850

There is another repository linked at the end, that implements the resize handle: https://github.com/Sphinxxxx/cm-resize

**Comment by n-riesco** [comment]
Thank you so much for the links.

**Comment by lunakid** [comment]
I've just [described in a comment](https://github.com/codemirror/CodeMirror/issues/850#issuecomment-373010997) a new implementation, which is the simplest yet, and does not need any JS drag-and-drop or custom drawing tricks, but relies on simpler, more straightforward and robust HTML5 features instead.

(Because of that, browsers, which don't support those (pretty standard) features yet, will just have no resize, just as before, so no harm is done. And when they catch up, resize will just start working for them, too. Edge is one of those, BTW.)

*(I posted to that other issue, #850, because the most relevant & valuable pieces of information related to this topic have already been there, including the most viable previous solutions. These issues should be merged, preferably by closing this one and reopening the other.)*

**Comment by n-riesco** [comment]
@lunakid Thank you for the link!

I'm planning to address this issue when we replace `react-codemirror` with `react-codemirror2` (issue #401).

**Comment by lunakid** [comment]
Great!
(BTW, I removed from my comment above a confusing remark about issue merging, which got there by mistake. :) )
