### ISSUE TITLE
Typing in the SQL editor should not be laggy from heavy repaints of the chart

### ISSUE THREAD

**Issue by kcolton** [plotly/falcon-sql-client#360]
It was quite frustrating to see the Falcon SQL Client have so much potential but be so difficult to use from severe performance issues. Had a suspicion it was an Electron app and was relieved to find that was true.

Here is the experience I was having when the Chart is open, which it is by default, for a new query:
https://jumpshare.com/v/37oThPPeXPgVvCAGwH5Q

I have Paint Flashing and Layer Borders enabled in Dev Tools. It may be hard to tell from the video, but while the chart is open the query editor is simply unusable. Originally I thought it might be the autocomplete / highlighting which may still be a source of some additional delay, but switching to the table view is _much_ better. It's not great, and I can imagine it being unusable on a slower machine.

Does anyone else get similar experience? My setup is not unique in anyway:

* OSX High Sierra - 10.13.2
* MBP (Retina, 15-inch, Mid 2015)
* 16 GB RAM
* AMD Radeon R9 M370X 2GB + Intel Iris Pro 1535MB
  _configured to always use dedicated_

If i'm not alone, would be happy to join or start a task force to tackle these performance optimizations. This is well within my wheelhouse and aligns with current work interests. 

I searched through the issues, but didn't see anything particularly on this. Anyone already working on?

**Comment by n-riesco** [comment]
> If i'm not alone, would be happy to join or start a task force to tackle these performance optimizations. This is well within my wheelhouse and aligns with current work interests.

This would be great. At the moment, I'm juggling on so many fronts maintaining Falcon, that all help is appreciated.

> I searched through the issues, but didn't see anything particularly on this. Anyone already working on?

I've looked into it, but I've only been able to reproduce this issue twice (even though I'm developing on a VM with 4GB RAM).

I'm already aware that the react app is causing SQL duplicated requests to build the table preview (but this doesn't explain the issue you see).

The video you've posted suggests the issue it's caused by redrawing the chart unnecessarily. I'd really welcome a PR to prevent this.

Thanks a lot for looking into this.

**Comment by jackparmer** [comment]
Falcon's current charting tool was meant to be a stopgap for https://github.com/plotly/react-plotly.js-editor. Swapping out the charting tool may be the best starting point since this is imminent anyway: https://github.com/plotly/falcon-sql-client/issues/350
